### ISSUE TITLE
error on Ubuntu, when trying to cythonize e_step_cy.pyx

### ISSUE THREAD

**Issue by shabnamkadir** [kwikteam/global_superclustering#4]
```
~/globalphy/global_superclustering/global_code$ python setup.py build_ext --inplace
Compiling e_step_cy.pyx because it changed.
Cythonizing e_step_cy.pyx
Compiler crash in ExpandInplaceOperators

ModuleNode.body = StatListNode(e_step_cy.pyx:7:0)
StatListNode.stats[4] = StatListNode(e_step_cy.pyx:14:6)
StatListNode.stats[0] = FusedCFuncDefNode(e_step_cy.pyx:14:6,
    defaults = [...]/7,
    fused_compound_types = [...]/2,
    match = "dest_sig[{{dest_sig_idx}}] = '{{specialized_type_name}}'",
    no_match = 'dest_sig[{{dest_sig_idx}}] = None',
    nodes = [...]/6,
    specialized_pycfuncs = [...]/6)
FusedCFuncDefNode.stats[1] = CFuncDefNode(e_step_cy.pyx:14:6,
    args = [...]/7,
    modifiers = [...]/0,
    overridable = 1,
    visibility = 'private')
CFuncDefNode.body = StatListNode(e_step_cy.pyx:21:4)
StatListNode.stats[0] = ForInStatNode(e_step_cy.pyx:22:4)
ForInStatNode.body = StatListNode(e_step_cy.pyx:23:8)
StatListNode.stats[1] = ForInStatNode(e_step_cy.pyx:24:8)
ForInStatNode.body = StatListNode(e_step_cy.pyx:25:12)
StatListNode.stats[0] = IfStatNode(e_step_cy.pyx:25:12)
IfStatNode.if_clauses[0] = IfClauseNode(e_step_cy.pyx:25:15)
IfClauseNode.body = StatListNode(e_step_cy.pyx:26:42)
StatListNode.stats[0] = InPlaceAssignmentNode(e_step_cy.pyx:26:42,
    operator = '+')
File 'UtilNodes.py', line 143, in __init__: ResultRefNode(may_hold_none = True,
    result_is_used = True,
    use_managed_ref = True)

Compiler crash traceback from this point on:
  File "/home/skadir/.conda/envs/globalphy/lib/python3.4/site-packages/Cython/Compiler/UtilNodes.py", line 143, in __init__
    assert self.pos is not None
AssertionError: 
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    ext_modules = cythonize("*.pyx")
  File "/home/skadir/.conda/envs/globalphy/lib/python3.4/site-packages/Cython/Build/Dependencies.py", line 865, in cythonize
    cythonize_one(*args[1:])
  File "/home/skadir/.conda/envs/globalphy/lib/python3.4/site-packages/Cython/Build/Dependencies.py", line 985, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: e_step_cy.pyx

```

Any ideas @thesamovar, @rossant, @nippoo ?

**Comment by thesamovar** [comment]
Try removing the in-place operator in that file since that's what seems to be causing the crash?
